---
- name: Install Nginx
  yum: name=nginx state=latest

- name: Install Nginx conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Create Nginx sites-available
  file: path=/etc/nginx/sites-available state=directory

- name: Create Nginx sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory
