- name: apply common config
  hosts: all
  roles:
    - common

- name: set up and run mailserver
  hosts: mail
  roles:
    - mail

- name: set up and run nhynes.com
  hosts: web
  roles:
    - web

- name: install home environment
  hosts: home
  roles:
    - home
