---
- name: Install Nginx
  yum: name=nginx state=latest

- name: Clone nhynes.com
  git: repo=https://github.com/nhynes/nhynes.com dest=/srv/nhynes.com depth=1

- name: Assign permissions to nhynes.com repo
  file: path=/srv/nhynes.com state=directory group=nginx mode=g+r recurse=yes

- name: Add nhynes.com to Nginx sites-available
  file: src=/srv/nhynes.com/nginx.conf dest=/etc/nginx/sites-available/nhynes.com state=link
  notify:
    - restart nginx

- name: Link nhynes.com into Nginx sites-enabled
  file: src=/etc/nginx/sites-available/nhynes.com dest=/etc/nginx/sites-enabled/nhynes.com state=link
  notify:
    - restart nginx
